# This is a basic workflow to help you get started with Actions

name: Github actions maven build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B --file pom.xml

      - name: List the current directory
        run: ls -a

      - name: Target folder
        run: 
          cd target
          ls -a
